import { ModelCapability, UniversalUsage } from '../ir/types.js';

export const MODEL_CATALOG: Record<string, ModelCapability> = {
  // OpenAI Models
  'gpt-4o': {
    id: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o (Omni)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10.0,
  },
  'gpt-4o-mini': {
    id: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o Mini',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.15,
    outputCostPerMillion: 0.6,
  },
  'o3-mini': {
    id: 'o3-mini',
    provider: 'openai',
    displayName: 'o3 Mini Reasoning',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.1,
    outputCostPerMillion: 4.4,
  },

  // Anthropic Models
  'claude-sonnet-5': {
    id: 'claude-sonnet-5',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 5',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-sonnet-4-5-20250929': {
    id: 'claude-sonnet-4-5-20250929',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.5',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-haiku-4-5-20251001': {
    id: 'claude-haiku-4-5-20251001',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.8,
    outputCostPerMillion: 4.0,
  },
  'claude-3-5-sonnet-20241022': {
    id: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-3-5-haiku-20241022': {
    id: 'claude-3-5-haiku-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.8,
    outputCostPerMillion: 4.0,
  },

  // Google Gemini Models
  'gemini-flash-latest': {
    id: 'gemini-flash-latest',
    provider: 'gemini',
    displayName: 'Gemini Flash (Latest)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-pro-latest': {
    id: 'gemini-pro-latest',
    provider: 'gemini',
    displayName: 'Gemini Pro (Latest)',
    contextWindow: 2000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 5.0,
  },
  'gemini-1.5-pro': {
    id: 'gemini-1.5-pro',
    provider: 'gemini',
    displayName: 'Gemini 1.5 Pro',
    contextWindow: 2000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 5.0,
  },
  'gemini-1.5-flash': {
    id: 'gemini-1.5-flash',
    provider: 'gemini',
    displayName: 'Gemini 1.5 Flash',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-2.0-flash': {
    id: 'gemini-2.0-flash',
    provider: 'gemini',
    displayName: 'Gemini 2.0 Flash',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.1,
    outputCostPerMillion: 0.4,
  },

  // Groq Live Models
  'qwen/qwen3.6-27b': {
    id: 'qwen/qwen3.6-27b',
    provider: 'groq',
    displayName: 'Groq Qwen 3.6 27B',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },
  'openai/gpt-oss-120b': {
    id: 'openai/gpt-oss-120b',
    provider: 'groq',
    displayName: 'Groq GPT-OSS 120B',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },

  // Groq Ultra-Fast Models
  'llama-3.3-70b-versatile': {
    id: 'llama-3.3-70b-versatile',
    provider: 'groq',
    displayName: 'Groq Llama 3.3 70B (Ultra-Fast)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },
  'deepseek-r1-distill-llama-70b': {
    id: 'deepseek-r1-distill-llama-70b',
    provider: 'groq',
    displayName: 'Groq DeepSeek-R1 Distill 70B',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },

  // xAI direct model. Additional models available to the user's account are
  // populated dynamically from the authenticated xAI language-model catalogue.
  'grok-4.6': {
    id: 'grok-4.6',
    provider: 'xai',
    displayName: 'xAI Grok 4.6',
    contextWindow: 500000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 2.0,
    outputCostPerMillion: 6.0,
  },

  // DeepSeek Direct Models
  'deepseek-chat': {
    id: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek V3 (Chat)',
    contextWindow: 64000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.14,
    outputCostPerMillion: 0.28,
  },
  'deepseek-reasoner': {
    id: 'deepseek-reasoner',
    provider: 'deepseek',
    displayName: 'DeepSeek R1 (Reasoning)',
    contextWindow: 64000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.55,
    outputCostPerMillion: 2.19,
  },

  // Qwen / DashScope Direct Models (Alibaba Cloud)
  'qwen-max': {
    id: 'qwen-max',
    provider: 'qwen',
    displayName: 'Qwen Max (Alibaba Cloud)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.60,
    outputCostPerMillion: 6.40,
  },
  'qwen-plus': {
    id: 'qwen-plus',
    provider: 'qwen',
    displayName: 'Qwen Plus',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.40,
    outputCostPerMillion: 1.20,
  },
  'qwen-turbo': {
    id: 'qwen-turbo',
    provider: 'qwen',
    displayName: 'Qwen Turbo (1M Context)',
    contextWindow: 1000000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.05,
    outputCostPerMillion: 0.20,
  },
  'qwen2.5-coder-32b-instruct': {
    id: 'qwen2.5-coder-32b-instruct',
    provider: 'qwen',
    displayName: 'Qwen 2.5 Coder 32B Instruct',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.25,
    outputCostPerMillion: 1.00,
  },
  'qwq-32b': {
    id: 'qwq-32b',
    provider: 'qwen',
    displayName: 'QwQ 32B (Reasoning Model)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.30,
    outputCostPerMillion: 1.20,
  },
  'qwen-vl-max': {
    id: 'qwen-vl-max',
    provider: 'qwen',
    displayName: 'Qwen VL Max (Multimodal Vision)',
    contextWindow: 131072,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.60,
    outputCostPerMillion: 6.40,
  },

  // GitHub Models (Free Marketplace Tier)
  'github/gpt-4o': {
    id: 'github/gpt-4o',
    provider: 'github',
    displayName: 'GitHub GPT-4o (Free Tier)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/gpt-4o-mini': {
    id: 'github/gpt-4o-mini',
    provider: 'github',
    displayName: 'GitHub GPT-4o Mini (Free Tier)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/o3-mini': {
    id: 'github/o3-mini',
    provider: 'github',
    displayName: 'GitHub o3-Mini (Free Tier)',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/deepseek-r1': {
    id: 'github/deepseek-r1',
    provider: 'github',
    displayName: 'GitHub DeepSeek R1 (Free Tier)',
    contextWindow: 64000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/meta-llama-3.3-70b': {
    id: 'github/meta-llama-3.3-70b',
    provider: 'github',
    displayName: 'GitHub Llama 3.3 70B (Free Tier)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // OpenRouter's zero-cost router dynamically selects a compatible free model.
  'openrouter/free': {
    id: 'openrouter/free',
    provider: 'openrouter',
    displayName: 'OpenRouter Free Models Router',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // Free stealth preview exposed through OpenRouter. Keep this explicit so
  // OpenAI-compatible clients can request the short slug as well as the live
  // catalogue route ID (openrouter::stealth/ox-alpha).
  'stealth/ox-alpha': {
    id: 'stealth/ox-alpha',
    provider: 'openrouter',
    displayName: 'Ox Alpha (Free Preview)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // Mock Models for zero-cost test suite & sandbox
  'mock-gpt-4o': {
    id: 'mock-gpt-4o',
    provider: 'mock',
    displayName: 'Mock GPT-4o (Simulated)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10.0,
  },
  'mock-claude-3-5-sonnet': {
    id: 'mock-claude-3-5-sonnet',
    provider: 'mock',
    displayName: 'Mock Claude 3.5 Sonnet (Simulated)',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'mock-gemini-1-5-flash': {
    id: 'mock-gemini-1-5-flash',
    provider: 'mock',
    displayName: 'Mock Gemini 1.5 Flash (Simulated)',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'mock-o3-mini': {
    id: 'mock-o3-mini',
    provider: 'mock',
    displayName: 'Mock o3-Mini (Simulated)',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.1,
    outputCostPerMillion: 4.4,
  },
  'mock-fail-429': {
    id: 'mock-fail-429',
    provider: 'mock',
    displayName: 'Mock Fault Injector (429 Rate Limit)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
};

export function calculateEstimatedCost(modelId: string, usage: UniversalUsage): number {
  const cap = MODEL_CATALOG[modelId];
  if (!cap) return 0;
  const inputCost = (usage.prompt_tokens / 1_000_000) * cap.inputCostPerMillion;
  const outputCost = (usage.completion_tokens / 1_000_000) * cap.outputCostPerMillion;
  return Number((inputCost + outputCost).toFixed(6));
}
