import { ModelCapability, UniversalUsage } from '../ir/types.js';

export const MODEL_CATALOG: Record<string, ModelCapability> = {
  // OpenAI Models
  'gpt-4o': {
    id: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o (Omni)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10.0,
  },
  'gpt-4o-mini': {
    id: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o Mini',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.15,
    outputCostPerMillion: 0.6,
  },
  'o3-mini': {
    id: 'o3-mini',
    provider: 'openai',
    displayName: 'o3 Mini Reasoning',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.1,
    outputCostPerMillion: 4.4,
  },

  // Anthropic Models
  'claude-sonnet-5': {
    id: 'claude-sonnet-5',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 5',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-sonnet-4-5-20250929': {
    id: 'claude-sonnet-4-5-20250929',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.5',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-haiku-4-5-20251001': {
    id: 'claude-haiku-4-5-20251001',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.8,
    outputCostPerMillion: 4.0,
  },
  'claude-3-5-sonnet-20241022': {
    id: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'claude-3-5-haiku-20241022': {
    id: 'claude-3-5-haiku-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.8,
    outputCostPerMillion: 4.0,
  },

  // Google Gemini Models
  'gemini-flash-latest': {
    id: 'gemini-flash-latest',
    provider: 'gemini',
    displayName: 'Gemini Flash (Latest)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-pro-latest': {
    id: 'gemini-pro-latest',
    provider: 'gemini',
    displayName: 'Gemini Pro (Latest)',
    contextWindow: 2000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 5.0,
  },
  'gemini-1.5-pro': {
    id: 'gemini-1.5-pro',
    provider: 'gemini',
    displayName: 'Gemini 1.5 Pro',
    contextWindow: 2000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 5.0,
  },
  'gemini-1.5-flash': {
    id: 'gemini-1.5-flash',
    provider: 'gemini',
    displayName: 'Gemini 1.5 Flash',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-3.6-flash': {
    id: 'gemini-3.6-flash',
    provider: 'gemini',
    displayName: 'Gemini 3.6 Flash (Next-Gen Free Tier)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-3.5-flash': {
    id: 'gemini-3.5-flash',
    provider: 'gemini',
    displayName: 'Gemini 3.5 Flash (Free Tier)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'gemini-3.5-flash-lite': {
    id: 'gemini-3.5-flash-lite',
    provider: 'gemini',
    displayName: 'Gemini 3.5 Flash Lite (Ultra Fast Free Tier)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.0375,
    outputCostPerMillion: 0.15,
  },
  'gemini-3.1-flash-lite': {
    id: 'gemini-3.1-flash-lite',
    provider: 'gemini',
    displayName: 'Gemini 3.1 Flash Lite',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.0375,
    outputCostPerMillion: 0.15,
  },
  'gemini-2.5-flash': {
    id: 'gemini-2.5-flash',
    provider: 'gemini',
    displayName: 'Gemini 2.5 Flash (Auto-maps to 3.6 Flash)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },

  // Groq Live Models
  'qwen/qwen3.6-27b': {
    id: 'qwen/qwen3.6-27b',
    provider: 'groq',
    displayName: 'Groq Qwen 3.6 27B',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },
  'openai/gpt-oss-120b': {
    id: 'openai/gpt-oss-120b',
    provider: 'groq',
    displayName: 'Groq GPT-OSS 120B',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },

  // Groq Ultra-Fast Models
  'qwen/qwen3.8-27b': {
    id: 'qwen/qwen3.8-27b',
    provider: 'groq',
    displayName: 'Groq Qwen 3.8 27B (Ultra-Fast)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },
  'groq/compound': {
    id: 'groq/compound',
    provider: 'groq',
    displayName: 'Groq Compound (Agentic Reasoning)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.59,
    outputCostPerMillion: 0.79,
  },
  'groq/compound-mini': {
    id: 'groq/compound-mini',
    provider: 'groq',
    displayName: 'Groq Compound Mini (Fast)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.29,
    outputCostPerMillion: 0.49,
  },

  // xAI direct model. Additional models available to the user's account are
  // populated dynamically from the authenticated xAI language-model catalogue.
  'grok-4.6': {
    id: 'grok-4.6',
    provider: 'xai',
    displayName: 'xAI Grok 4.6',
    contextWindow: 500000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 2.0,
    outputCostPerMillion: 6.0,
  },

  // DeepSeek Direct Models
  'deepseek-chat': {
    id: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek V3 (Chat)',
    contextWindow: 64000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.14,
    outputCostPerMillion: 0.28,
  },
  'deepseek-v4-flash': {
    id: 'deepseek-v4-flash',
    provider: 'deepseek',
    displayName: 'DeepSeek V4 Flash',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.14,
    outputCostPerMillion: 0.28,
  },
  'deepseek-v4-pro': {
    id: 'deepseek-v4-pro',
    provider: 'deepseek',
    displayName: 'DeepSeek V4 Pro',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.55,
    outputCostPerMillion: 2.19,
  },



  // Cerebras Ultra-Fast Cloud (Free Tier, 1800+ tok/s)
  'cerebras/llama-3.3-70b': {
    id: 'cerebras/llama-3.3-70b',
    provider: 'cerebras',
    displayName: 'Cerebras Llama 3.3 70B (1,800+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'cerebras/llama3.1-8b': {
    id: 'cerebras/llama3.1-8b',
    provider: 'cerebras',
    displayName: 'Cerebras Llama 3.1 8B (2,000+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'cerebras/deepseek-r1-distill-llama-70b': {
    id: 'cerebras/deepseek-r1-distill-llama-70b',
    provider: 'cerebras',
    displayName: 'Cerebras DeepSeek R1 70B (Ultra-Speed Reasoning)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'cerebras/gemma-4-31b': {
    id: 'cerebras/gemma-4-31b',
    provider: 'cerebras',
    displayName: 'Cerebras Gemma 4 31B (2,000+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'gemma-4-31b': {
    id: 'gemma-4-31b',
    provider: 'cerebras',
    displayName: 'Cerebras Gemma 4 31B (2,000+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'cerebras/gpt-oss-120b': {
    id: 'cerebras/gpt-oss-120b',
    provider: 'cerebras',
    displayName: 'Cerebras GPT-OSS 120B (1,800+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'cerebras/qwen-3.8-27b': {
    id: 'cerebras/qwen-3.8-27b',
    provider: 'cerebras',
    displayName: 'Cerebras Qwen 3.8 27B (2,200+ tok/s)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // NVIDIA NIM Cloud (build.nvidia.com)
  'nvidia/meta/llama-3.1-405b-instruct': {
    id: 'nvidia/meta/llama-3.1-405b-instruct',
    provider: 'nvidia',
    displayName: 'NVIDIA Llama 3.1 405B (Mammoth 405B Frontier)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'nvidia/meta/llama-3.3-70b-instruct': {
    id: 'nvidia/meta/llama-3.3-70b-instruct',
    provider: 'nvidia',
    displayName: 'NVIDIA Llama 3.3 70B Instruct',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'nvidia/nvidia/nemotron-4-340b-instruct': {
    id: 'nvidia/nvidia/nemotron-4-340b-instruct',
    provider: 'nvidia',
    displayName: 'NVIDIA Nemotron-4 340B Instruct',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'nvidia/deepseek-ai/deepseek-r1': {
    id: 'nvidia/deepseek-ai/deepseek-r1',
    provider: 'nvidia',
    displayName: 'NVIDIA DeepSeek R1 (671B Full Reasoning)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // GitHub Models (Free Marketplace Tier)
  'github/gpt-4o': {
    id: 'github/gpt-4o',
    provider: 'github',
    displayName: 'GitHub GPT-4o (Free Tier)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/gpt-4o-mini': {
    id: 'github/gpt-4o-mini',
    provider: 'github',
    displayName: 'GitHub GPT-4o Mini (Free Tier)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/o3-mini': {
    id: 'github/o3-mini',
    provider: 'github',
    displayName: 'GitHub o3-Mini (Free Tier)',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/deepseek-r1': {
    id: 'github/deepseek-r1',
    provider: 'github',
    displayName: 'GitHub DeepSeek R1 (Free Tier)',
    contextWindow: 64000,
    supportsVision: false,
    supportsTools: false,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'github/meta-llama-3.3-70b': {
    id: 'github/meta-llama-3.3-70b',
    provider: 'github',
    displayName: 'GitHub Llama 3.3 70B (Free Tier)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // OpenRouter's zero-cost router dynamically selects a compatible free model.
  'openrouter/free': {
    id: 'openrouter/free',
    provider: 'openrouter',
    displayName: 'OpenRouter Free Models Router',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // Free stealth preview exposed through OpenRouter. Keep this explicit so
  // OpenAI-compatible clients can request the short slug as well as the live
  // catalogue route ID (openrouter::stealth/ox-alpha).
  'stealth/ox-alpha': {
    id: 'stealth/ox-alpha',
    provider: 'openrouter',
    displayName: 'Ox Alpha (Free Preview)',
    contextWindow: 1048576,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // Mock Models for zero-cost test suite & sandbox
  'mock-gpt-4o': {
    id: 'mock-gpt-4o',
    provider: 'mock',
    displayName: 'Mock GPT-4o (Simulated)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10.0,
  },
  'mock-claude-3-5-sonnet': {
    id: 'mock-claude-3-5-sonnet',
    provider: 'mock',
    displayName: 'Mock Claude 3.5 Sonnet (Simulated)',
    contextWindow: 200000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 3.0,
    outputCostPerMillion: 15.0,
  },
  'mock-gemini-1-5-flash': {
    id: 'mock-gemini-1-5-flash',
    provider: 'mock',
    displayName: 'Mock Gemini 1.5 Flash (Simulated)',
    contextWindow: 1000000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.075,
    outputCostPerMillion: 0.3,
  },
  'mock-o3-mini': {
    id: 'mock-o3-mini',
    provider: 'mock',
    displayName: 'Mock o3-Mini (Simulated)',
    contextWindow: 200000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.1,
    outputCostPerMillion: 4.4,
  },
  'mock-fail-429': {
    id: 'mock-fail-429',
    provider: 'mock',
    displayName: 'Mock Fault Injector (429 Rate Limit)',
    contextWindow: 128000,
    supportsVision: true,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // UnoRouter Free Tier Models (unorouter.com)
  'glm-5.3-search:free': {
    id: 'glm-5.3-search:free',
    provider: 'unorouter',
    displayName: 'UnoRouter GLM 5.3 Search (Free · Tools · Search)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'unorouter/glm-5.3-search:free': {
    id: 'unorouter/glm-5.3-search:free',
    provider: 'unorouter',
    displayName: 'UnoRouter GLM 5.3 Search (Free · Tools · Search)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'unorouter::glm-5.3-search:free': {
    id: 'unorouter::glm-5.3-search:free',
    provider: 'unorouter',
    displayName: 'UnoRouter GLM 5.3 Search (Free · Tools · Search)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'unorouter/qwen/qwen-2.5-coder-32b-instruct:free': {
    id: 'unorouter/qwen/qwen-2.5-coder-32b-instruct:free',
    provider: 'unorouter',
    displayName: 'UnoRouter Qwen 2.5 Coder 32B (Free · Tools)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'unorouter/deepseek/deepseek-r1:free': {
    id: 'unorouter/deepseek/deepseek-r1:free',
    provider: 'unorouter',
    displayName: 'UnoRouter DeepSeek R1 (Free · Tools)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'unorouter/meta-llama/llama-3.3-70b-instruct:free': {
    id: 'unorouter/meta-llama/llama-3.3-70b-instruct:free',
    provider: 'unorouter',
    displayName: 'UnoRouter Llama 3.3 70B (Free · Tools)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },

  // Qwen / DashScope Models (Alibaba Cloud)
  'qwen/qwen-2.5-coder-32b-instruct': {
    id: 'qwen/qwen-2.5-coder-32b-instruct',
    provider: 'qwen',
    displayName: 'Qwen 2.5 Coder 32B Instruct (DashScope)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.60,
  },
  'qwen/qwen-plus': {
    id: 'qwen/qwen-plus',
    provider: 'qwen',
    displayName: 'Qwen Plus (Balanced Frontier)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.40,
    outputCostPerMillion: 1.20,
  },
  'qwen/qwen-max': {
    id: 'qwen/qwen-max',
    provider: 'qwen',
    displayName: 'Qwen Max (Deep Reasoning & Analysis)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.60,
    outputCostPerMillion: 4.80,
  },
  'qwen-2.5-coder-32b-instruct': {
    id: 'qwen-2.5-coder-32b-instruct',
    provider: 'qwen',
    displayName: 'Qwen 2.5 Coder 32B Instruct',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.60,
  },
  'qwen-plus': {
    id: 'qwen-plus',
    provider: 'qwen',
    displayName: 'Qwen Plus',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.40,
    outputCostPerMillion: 1.20,
  },
  'qwen-max': {
    id: 'qwen-max',
    provider: 'qwen',
    displayName: 'Qwen Max',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 1.60,
    outputCostPerMillion: 4.80,
  },
  // xKiro Models
  'xkiro/deepseek/deepseek-r1:free': {
    id: 'xkiro/deepseek/deepseek-r1:free',
    provider: 'xkiro',
    displayName: 'xKiro DeepSeek R1 (Free)',
    contextWindow: 65536,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  // Cloudflare Workers AI Models
  'cloudflare/@cf/meta/llama-3.3-70b-instruct': {
    id: 'cloudflare/@cf/meta/llama-3.3-70b-instruct',
    provider: 'cloudflare',
    displayName: 'Cloudflare Llama 3.3 70B Instruct',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  // AI/ML API Models
  'aimlapi/deepseek/deepseek-r1': {
    id: 'aimlapi/deepseek/deepseek-r1',
    provider: 'aimlapi',
    displayName: 'AI/ML API DeepSeek R1',
    contextWindow: 65536,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.55,
    outputCostPerMillion: 2.19,
  },
  // GMI Cloud Models
  'gmicloud/deepseek-ai/DeepSeek-R1': {
    id: 'gmicloud/deepseek-ai/DeepSeek-R1',
    provider: 'gmicloud',
    displayName: 'GMI Cloud DeepSeek R1',
    contextWindow: 65536,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.55,
    outputCostPerMillion: 2.19,
  },
  // Inception Labs (Diffusion LLMs)
  'inception/mercury-2.5': {
    id: 'inception/mercury-2.5',
    provider: 'inception',
    displayName: 'Inception Labs Mercury 2.5 (Diffusion LLM)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.25,
    outputCostPerMillion: 1.00,
  },
  'inception::mercury-2.5': {
    id: 'inception::mercury-2.5',
    provider: 'inception',
    displayName: 'Inception Labs Mercury 2.5 (Diffusion LLM)',
    contextWindow: 128000,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.25,
    outputCostPerMillion: 1.00,
  },
  'inception/mercury-2': {
    id: 'inception/mercury-2',
    provider: 'inception',
    displayName: 'Inception Labs Mercury 2',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.80,
  },
  'inception::mercury-2': {
    id: 'inception::mercury-2',
    provider: 'inception',
    displayName: 'Inception Labs Mercury 2',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.80,
  },
  'inception/mercury-edit-2': {
    id: 'inception/mercury-edit-2',
    provider: 'inception',
    displayName: 'Inception Labs Mercury Edit 2',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.80,
  },
  'inception::mercury-edit-2': {
    id: 'inception::mercury-edit-2',
    provider: 'inception',
    displayName: 'Inception Labs Mercury Edit 2',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.20,
    outputCostPerMillion: 0.80,
  },
  'inception/mercury-coder-small': {
    id: 'inception/mercury-coder-small',
    provider: 'inception',
    displayName: 'Inception Labs Mercury Coder Small',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.15,
    outputCostPerMillion: 0.60,
  },
  'inception::mercury-coder-small': {
    id: 'inception::mercury-coder-small',
    provider: 'inception',
    displayName: 'Inception Labs Mercury Coder Small',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0.15,
    outputCostPerMillion: 0.60,
  },
  // Atria ASI (Dawn 744B Agentic Foundation Model)
  'atria/Atria-Dawn-Preview': {
    id: 'atria/Atria-Dawn-Preview',
    provider: 'atria',
    displayName: 'Atria Dawn Preview (744B Agentic MoE)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'atria::Atria-Dawn-Preview': {
    id: 'atria::Atria-Dawn-Preview',
    provider: 'atria',
    displayName: 'Atria Dawn Preview (744B Agentic MoE)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'atria/atria-dawn-preview': {
    id: 'atria/atria-dawn-preview',
    provider: 'atria',
    displayName: 'Atria Dawn Preview',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'atria::atria-dawn-preview': {
    id: 'atria::atria-dawn-preview',
    provider: 'atria',
    displayName: 'Atria Dawn Preview',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'atria/Atria-Dawn': {
    id: 'atria/Atria-Dawn',
    provider: 'atria',
    displayName: 'Atria Dawn (744B MoE)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'atria::Atria-Dawn': {
    id: 'atria::Atria-Dawn',
    provider: 'atria',
    displayName: 'Atria Dawn (744B MoE)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'Atria-Dawn-Preview': {
    id: 'Atria-Dawn-Preview',
    provider: 'atria',
    displayName: 'Atria Dawn Preview (744B Agentic MoE)',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  'Atria-Dawn': {
    id: 'Atria-Dawn',
    provider: 'atria',
    displayName: 'Atria Dawn',
    contextWindow: 131072,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0.50,
    outputCostPerMillion: 2.00,
  },
  // Local Models
  'nexus-qwen3-brain': {
    id: 'nexus-qwen3-brain',
    provider: 'local',
    displayName: 'Nexus Brain (Qwen3-8B)',
    contextWindow: 8192,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'local/nexus-qwen3-brain': {
    id: 'local/nexus-qwen3-brain',
    provider: 'local',
    displayName: 'Nexus Brain (Qwen3-8B)',
    contextWindow: 8192,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'qwen2.5-coder:1.5b': {
    id: 'qwen2.5-coder:1.5b',
    provider: 'local',
    displayName: 'Qwen 2.5 Coder 1.5B (157 toks/s)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'sovereign-coder:1.5b': {
    id: 'sovereign-coder:1.5b',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:1.5B (Offline Draft Engine)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'local/sovereign-coder:1.5b': {
    id: 'local/sovereign-coder:1.5b',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:1.5B (Offline Draft Engine)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'sovereign-coder:14b': {
    id: 'sovereign-coder:14b',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:14B (Offline Deep Architect)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'local/sovereign-coder:14b': {
    id: 'local/sovereign-coder:14b',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:14B (Offline Deep Architect)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'sovereign-coder:brain': {
    id: 'sovereign-coder:brain',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:Brain (1B Skill Injected)',
    contextWindow: 8192,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'local/sovereign-coder:brain': {
    id: 'local/sovereign-coder:brain',
    provider: 'local',
    displayName: '👑 ﹩overeign-coder:Brain (1B Skill Injected)',
    contextWindow: 8192,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'gemma2:2b': {
    id: 'gemma2:2b',
    provider: 'local',
    displayName: 'Google Gemma 2 2B (109 toks/s)',
    contextWindow: 8192,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: false,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'speculative': {
    id: 'speculative',
    provider: 'local',
    displayName: 'Speculative Draft & Verify (157 toks/s + Verifier)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'local/hermes-3:8b': {
    id: 'local/hermes-3:8b',
    provider: 'local',
    displayName: '🧠 Hermes 3 8B (Tool-Calling & Agentic)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
  'hermes3:8b': {
    id: 'hermes3:8b',
    provider: 'local',
    displayName: '🧠 Nous Hermes 3 8B (Llama 3.1 Instruct)',
    contextWindow: 32768,
    supportsVision: false,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsReasoning: true,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
  },
};

export function calculateEstimatedCost(modelId: string, usage: UniversalUsage): number {
  const cleanId = (modelId || '').replace(/^[^:]+::/, '').replace(/^[^/]+\//, '');
  const cap = MODEL_CATALOG[modelId] || MODEL_CATALOG[cleanId];
  
  let inputPerM = cap ? cap.inputCostPerMillion : 0;
  let outputPerM = cap ? cap.outputCostPerMillion : 0;

  if (!cap) {
    if (cleanId.includes('deepseek')) {
      inputPerM = 0.14;
      outputPerM = 0.28;
    } else if (cleanId.includes('claude-3-5') || cleanId.includes('claude-sonnet')) {
      inputPerM = 3.0;
      outputPerM = 15.0;
    } else if (cleanId.includes('gpt-4o-mini')) {
      inputPerM = 0.15;
      outputPerM = 0.60;
    } else if (cleanId.includes('gpt-4o')) {
      inputPerM = 2.50;
      outputPerM = 10.00;
    } else if (cleanId.includes('gemini')) {
      inputPerM = 0.075;
      outputPerM = 0.30;
    }
  }

  const inputCost = ((usage.prompt_tokens || 0) / 1_000_000) * inputPerM;
  const outputCost = ((usage.completion_tokens || 0) / 1_000_000) * outputPerM;
  return Number((inputCost + outputCost).toFixed(6));
}
